"""Update embedding vector to 768 dimensions for Gemini

Revision ID: 00be0a9a9d35
Revises: 82984becbc35
Create Date: 2025-08-22 18:46:41.395472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '00be0a9a9d35'
down_revision: Union[str, Sequence[str], None] = '82984becbc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE subscriptions SET embedding = NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE subscriptions SET embedding = NULL")

    op.alter_column('subscriptions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
