"""Add ON DELETE CASCADE to channel_tags foreign keys

Revision ID: 3412354444ff
Revises: b69893bda5d1
Create Date: 2025-07-21 13:05:47.251772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3412354444ff'
down_revision: Union[str, Sequence[str], None] = 'b69893bda5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('channel_tags_tag_id_fkey'), 'channel_tags', type_='foreignkey')
    op.drop_constraint(op.f('channel_tags_channel_id_fkey'), 'channel_tags', type_='foreignkey')
    op.create_foreign_key(None, 'channel_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'channel_tags', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_tags', type_='foreignkey')
    op.drop_constraint(None, 'channel_tags', type_='foreignkey')
    op.create_foreign_key(op.f('channel_tags_channel_id_fkey'), 'channel_tags', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key(op.f('channel_tags_tag_id_fkey'), 'channel_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
