"""Add many-to-many relationship for message tags

Revision ID: 98eee1f6206b
Revises: 7edb0543e976
Create Date: 2025-07-25 10:51:17.902174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98eee1f6206b'
down_revision: Union[str, Sequence[str], None] = '7edb0543e976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
