"""decouple channel form tag and message

Revision ID: b69893bda5d1
Revises: 626ced32187a
Create Date: 2025-07-21 12:55:48.231621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69893bda5d1'
down_revision: Union[str, Sequence[str], None] = '626ced32187a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('channel_telegram_id', sa.BigInteger(), nullable=False))
    op.alter_column('messages', 'channel_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_messages_channel_telegram_id'), 'messages', ['channel_telegram_id'], unique=False)
    op.drop_constraint(op.f('messages_channel_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_channel_id_fkey'), 'messages', 'channels', ['channel_id'], ['id'])
    op.drop_index(op.f('ix_messages_channel_telegram_id'), table_name='messages')
    op.alter_column('messages', 'channel_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'channel_telegram_id')
    # ### end Alembic commands ###
